[package]
name = "anime-game-launcher"
version = "3.9.0"
description = "Anime Game launcher"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
homepage = "https://github.com/an-anime-team/an-anime-game-launcher"
repository = "https://github.com/an-anime-team/an-anime-game-launcher"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = "s"

[build-dependencies]
glib-build-tools = "0.18"

[dependencies.anime-launcher-sdk]
git = "https://github.com/cybik/anime-launcher-sdk"
tag = "99.1.11.1"
features = ["all", "genshin"]

# path = "../anime-launcher-sdk" # ! for dev purposes only

[dependencies]
relm4 = { version = "0.6.0", features = ["macros", "libadwaita"] }
gtk = { package = "gtk4", version = "0.6", features = ["v4_8"] }
adw = { package = "libadwaita", version = "0.4", features = ["v1_2"] }

rfd = { version = "0.11", features = ["xdg-portal"], default-features = false }
open = "5.0.0"
whatadistro = "0.1.0"

serde_json = "1.0"
anyhow = "1.0"
lazy_static = "1.4.0"
cached = { version = "0.44", features = ["proc_macro"] }
md-5 = { version = "0.10", features = ["asm"] }

tracing = "0.1"
tracing-subscriber = "0.3"

fluent-templates = "0.8"
unic-langid = "0.9"

human-panic = "1.1.5"
