[package]
name = "anime-game-launcher"
version = "3.6.0"
description = "Anime Game launcher"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = "s"

[build-dependencies]
glib-build-tools = "0.17"

[dependencies.anime-launcher-sdk]
git = "https://github.com/an-anime-team/anime-launcher-sdk"
tag = "1.2.4"
features = ["all", "genshin"]

# path = "../anime-launcher-sdk" # ! for dev purposes only

[dependencies]
relm4 = { version = "0.6.0-beta.1", features = ["macros", "libadwaita", "gnome_42"] }
gtk = { package = "gtk4", version = "0.6", features = ["v4_6"] }
adw = { package = "libadwaita", version = "0.3", features = ["v1_2"] }

rfd = { version = "0.11", features = ["xdg-portal"], default-features = false }
open = "4.0"

serde_json = "1.0"
anyhow = "1.0"
lazy_static = "1.4.0"
cached = { version = "0.43", features = ["proc_macro"] }
md-5 = { version = "0.10", features = ["asm"] }

tracing = "0.1"
tracing-subscriber = "0.3"

fluent-templates = "0.8"
unic-langid = "0.9"
